config/routes.rb
Rails.application.routes.draw do
  get "/", to: "pages#home"
  post "/", to: "users#index"
  # get '/users/search', to: 'users#search', as: 'search_users'
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/profile", to: "pages#profile"
  resources :users do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]
  patch "/booking/:id/update", to: "bookings#update_status", as: "booking_update_status"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :occasion
  belongs_to :escort, class_name: "User", foreign_key: "escort_id"
  belongs_to :renter, class_name: "User", foreign_key: "renter_id"

  has_many :reviews
end

app/models/occasion.rb
class Occasion < ApplicationRecord
  has_many :user_occasions
  has_many :users, through: :user_occasions
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "escort_id"
  belongs_to :user, class_name: "User", foreign_key: "renter_id"
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :user_occasions
  has_many :occasions, through: :user_occasions
  # This allows us to check the bookings the user has booked (not those they have been booked to escort on)
  has_many :bookings, class_name: "Booking", foreign_key: "renter_id"
  # "user.engagements" will display bookings that they are booked to escort on.
  has_many :engagements, class_name: "Booking", foreign_key: "escort_id"
  has_many :reviews, class_name: "Review", foreign_key: "escort_id"
end

app/models/user_occasion.rb
class UserOccasion < ApplicationRecord
  belongs_to :user
  belongs_to :occasion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :age, :gender, :location])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :age, :gender, :location])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def new
    @escort = User.find(params[:user_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @escort = User.find(params[:user_id])
    @booking.escort = @escort
    @booking.renter = current_user
    if @booking.save
      @booking = Booking.find(@booking.id)
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update_status
    @booking = Booking.find(params[:id])
    @booking.status = params[:status]
    @booking.save
    redirect_to bookings_path(tab: "engagements")
  end

  private

  def booking_params
    params.require(:booking).permit(:location, :date, :occasion_id, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :profile

  def home
    @user = User.new
  end

  def profile
    @user = User.find(current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    unless params[:user][:occasion] == ""
      @users = UserOccasion.where(occasion: Occasion.find_by(name: params[:user][:occasion])).map {|o| o.user}
    end
    age_range = params[:user][:age].split("-")
    unless params[:user][:age] == ""
      if age_range[1].to_i.positive?
        @users = User.where(age: age_range[0].to_i..age_range[1].to_i)
        @users = @users.select { |u| u.age >= age_range[0].to_i }
        @users = @users.select { |u| u.age <= age_range[1].to_i }
      else
        @users = @users.select { |u| u.age >= age_range[0].to_i }
      end
    end
    unless params[:user][:location] == ""
      @users = @users.select { |u| u.location == params[:user][:location] }
    end
    unless params[:user][:gender] == ""
      @users = @users.select { |u| u.gender == params[:user][:gender] }
    end
    unless params[:user][:date] == ""
      @users = @users.reject { |u| u.bookings.find { |d| d.date.to_s == params[:user][:date] } }
      @users = @users.reject { |u| u.engagements.find { |d| d.date.to_s == params[:user][:date] } }
    end

    if @users == []
      flash.alert = 'No users match your search query => showing all users'
      @users = User.all
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:location, :age, :event, :gender, :start_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1><%= current_user.full_name %>'s Bookings</h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= "active" if params[:tab] != "engagements" %>" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings" type="button" role="tab" aria-controls="bookings" aria-selected=<%= "false" if params[:tab] == "engagements" %> <%= tabindex="-1" if params[:tab] == "engagements" %>>Bookings</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= "active" if params[:tab] == "engagements" %>" id="engagements-tab" data-bs-toggle="tab" data-bs-target="#engagements" type="button" role="tab" aria-controls="engagements" aria-selected=<%= "true" if params[:tab] == "engagements" %>>Engagements</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade <%= "show active" if params[:tab] != "engagements" %>" id="bookings" role="tabpanel" aria-labelledby="bookings-tab">
  <p style="text-align: left">These listings are those that you have booked for others to join you:</p>
  <div class="card mb-3 border-success card_bg_opacity">
    <h2>Approved</h2>
      <ul style="list-style-type: none">
        <% current_user.bookings.each do |booking| %>
          <% if booking.status == "approved" %>
            <li class="mb-2">
              <strong><%= booking.escort.full_name %></strong> to accompany you for a <%= booking.occasion.name %>, in <%= booking.location %>, on <%= booking.date %>. <br>
              Status: <em><%= booking.status %></em>
            </li>
          <% end %>
        <% end %>
      </ul>
  </div>

  <div class="card mb-3 border-warning card_bg_opacity">
    <h2>Pending Review</h2>
    <ul style="list-style-type: none">
      <% current_user.bookings.each do |booking| %>
        <% if booking.status == "pending" %>
          <li class="mb-2">
            <strong><%= booking.escort.full_name %></strong> to accompany you for a <%= booking.occasion.name %>, in <%= booking.location %>, on <%= booking.date %>. <br>
            Status: <em><%= booking.status %></em>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class="card border-danger card_bg_opacity">
    <h2>Rejected</h2>
    <ul style="list-style-type: none">
      <% current_user.bookings.each do |booking| %>
        <% if booking.status == "rejected" %>
          <li class="mb-2">
            <strong><%= booking.escort.full_name %></strong> to accompany you for a <%= booking.occasion.name %>, in <%= booking.location %>, on <%= booking.date %>. <br>
            Status: <em><%= booking.status %></em>
          </li>
        <% end %>
      <% end %>
    </ul></div>
  </div>


  <div class="tab-pane fade <%= "show active" if params[:tab] == "engagements" %>" id="engagements" role="tabpanel" aria-labelledby="engagements-tab">
   <p style="text-align: left">These listings are those that you are being rented for:</p>
    <div class="card mb-3 border-success card_bg_opacity">
      <h2>Approved</h2>
      <ul style="list-style-type: none">
        <% current_user.engagements.each do |booking| %>
          <% if booking.status == "approved" %>
            <li class="mb-2">
              <strong>You</strong> are accompanying <strong><%= booking.renter.full_name %></strong> to a <%= booking.occasion.name %>, in <%= booking.location %>, on <%= booking.date %> <br>
              Status: <%= booking.status %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div class="card mb-3 border-warning card_bg_opacity">
      <h2>Pending Review</h2>
      <ul style="list-style-type: none">
        <% current_user.engagements.each do |booking| %>
          <% if booking.status == "pending" %>
            <li class="mb-2">
              <strong>You</strong> are accompanying <strong><%= booking.renter.full_name %></strong> to a <%= booking.occasion.name %>, in <%= booking.location %>, on <%= booking.date %> <br>
              Status: <%= booking.status %>
            </li>
            <div class="row justify-content-center">
              <%= link_to "Approve", booking_update_status_path(booking, status: "approved"), data: { turbo_method: :patch }, class: "btn btn-success card_bg_opacity mx-2", style: "width: 20%" %>
              <%= link_to "Reject", booking_update_status_path(booking, status: "rejected"), data: { turbo_method: :patch }, class: "btn btn-danger card_bg_opacity mx-2", style: "width: 20%" %>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div class="card border-danger card_bg_opacity">
      <h2>Rejected</h2>
      <ul style="list-style-type: none">
        <% current_user.engagements.each do |booking| %>
          <% if booking.status == "rejected" %>
            <li class="mb-2">
              <strong>You</strong> are accompanying <strong><%= booking.renter.full_name %></strong> to a <%= booking.occasion.name %>, in <%= booking.location %>, on <%= booking.date %> <br>
              Status: <%= booking.status %>
            </li>
            <div class="row justify-content-center">
              <%= link_to "Approve", booking_update_status_path(booking, status: "approved"), data: { turbo_method: :patch }, class: "btn btn-success card_bg_opacity mx-2", style: "width: 20%" %>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

</div>

app/views/bookings/new.html.erb
<div class="bg vh-100">
  <div class="container">
    <div class="filter d-flex justify-content-center">
    <div class="filter-form w-50 p-3">
    <div class="book">
  <h3 style="color: black;"> Book <%= @escort.full_name %></h3>
  </div>
    <%= simple_form_for [@escort, @booking] do |f| %>
    <%= f.input :location, :placeholder => 'Location', label: false%>
    <%= f.input :date, :placeholder => 'Date', label: false, html5: true  %>
    <%= f.association :occasion, collection: @escort.occasions, label: false, :placeholder => 'Occasion' %>
    <div class="work">
    <%= f.button :submit, :placeholder => 'Book', class:"text-white" %>
    </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="bt vh-100">
<div class="container-sm row justify-content-center">
  <div class="card-booking" style="width: 40%;">
    <div class="card-body">
      <h5 class="card-title-booking">Booking is ✅</h5>
      <p class="card-text"><small class="text-body-two">Here are the details</small></p>
      <p class="card-text" style="text-transform:capitalize;"><%= @booking.occasion.name %> with <%= User.find(@booking.escort_id).full_name %> in <%= @booking.location %> <br> date: <%= @booking.date %><br>
      Enjoy <%= User.find(@booking.renter_id).full_name %> !</p>
    </div>

  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPerson</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="bg-image">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="container vh-100">
    <div class="filter">
    <div class="filter-form">
    <h3>Match up for your next event</h3>
      <%= form_with model: @user, url: users_path, method: :get do |form| %>
        <%= form.select :location, (User.all.map {|u| u.location}).uniq, {include_blank: "Location"}, { class: "w-50 p-3" } %>
        <br>
        <%= form.select :age, ['18-25', '25-40', '40-60', '60+'] , {include_blank: "Age"}, { class: "w-50 p-3" } %>
        <br>
        <%= form.select :occasion, Occasion.all.map { |o| o.name } , {include_blank: "Event"}, { class: "w-50 p-3" }%>
        <br>
        <%= form.select :gender, ['male', 'female'] , {include_blank: "Gender"}, { class: "w-50 p-3" } %>
        <br>
        <div class="mb-2">
          <%= form.date_field :date, data: { controller: "datepicker" }, placeholder: "Date" %>
        </div>

        <div>
        <%= form.submit 'Connect', { class: "btn btn-primary btn-lg btn-block" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<h1><%= current_user.full_name %>'s Profile</h1>
<br />

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Profile info</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Your reviews</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false"><%= link_to " your bookings", bookings_path, class: "link"%></button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
     <%= simple_form_for @user, url: user_registration_path, method: :post do |f| %>
        <%= f.input :email, placeholder:current_user.email, input_html: {readonly: true} %>
        <%= f.input :password, placeholder:"*********", input_html: {readonly: true}%>
        <%= f.input :full_name, placeholder:current_user.full_name, input_html: {readonly: true} %>
        <%= f.input :age, placeholder:current_user.age, input_html: {readonly: true} %>
        <%= f.input :gender, placeholder:current_user.gender, input_html: {readonly: true} %>
        <%= f.input :location, placeholder:current_user.location, input_html: {readonly: true} %>
        <%= f.button :submit %>
      <% end %>
  </div>
  <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">  <h3><strong>Your reviews</strong> </h3>
    <br>
    <% current_user.reviews.each do |review| %>
    <p><strong>Review</strong></p>
    <% renter = User.find(review.renter_id)%>
    <p> By: <%= renter.full_name %></p>
    <% escort = User.find(review.escort_id)%>
    <p> To: <%= escort.full_name %></p>
    <p>Comment: <%= review.comment %></p>
    <p>Rating: <%= review.rating %></p>
    <% end %>
    </div>
  <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">...</div>
  <div class="tab-pane fade" id="disabled-tab-pane" role="tabpanel" aria-labelledby="disabled-tab" tabindex="0">...</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%# <%= image_tag "https://cdn.vectorstock.com/i/1000x1000/91/53/friends-or-partners-logo-element-business-vector-5159153.webp" %>
      <h3 class="navbar-text">Rent a Friend</h3>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://img.freepik.com/premium-photo/man-with-suit-tie-that-says-he-s-smiling_745528-2580.jpg?w=996", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h3>People available to join you for your occasion:</h3>
<div class="cards-index vh-100 ">

      <% @users.each do |user| %>
        <div class="user-infos-index mb-1 card_bg_opacity">
          <img class="imgindex" src="https://img.freepik.com/photos-premium/beau-garcon_559599-256.jpg" style="width:100%">
          <ul >
            <h4><strong><%= link_to user.full_name, user_path(user) %></strong></h4>
            <li><strong>Age: </strong><%= user.age %></li>
            <li><strong>Gender: </strong><%= user.gender %></li>
            <li><strong>Location: </strong><%= user.location %></li>
          </ul>
        </div>
      <% end %>

 </div>

app/views/users/show.html.erb
<%= link_to "<<", :back, class: 'linkhome text-white', style:"text-decoration: none;" %>
<br />
  <div class="cards card_bg_opacity">
  <img src="https://img.freepik.com/photos-premium/beau-garcon_559599-256.jpg" style="width:100%">
    <h3 class="pt-2"><strong><%= @user.full_name %></strong></h3>
      <div class="card-escort">
        <div class="user-infos">
            <p>Age: <%= @user.age %></p>
            <p>City: <%= @user.location %></p>
        </div>
        <h2 class="card-review">
              <p>Reviews</p>
              <div class="review-container">
                <% @user.reviews.each do |review| %>
                <p>"<%= review.comment %>" <span class="text-white-50"><em>- <%= User.find(review.renter_id).full_name %></em></span></p>
                <div class="rating">
                    <p>Rating: </p>
                    <% review.rating.times do %> <p>⭐️</p>
                    <% end %>
                </div>
                <p class="line">-----------</p>
                <% end %>
              </div>
        </h2>
  </div>
  <button><%= link_to "Book your companion", new_user_booking_path(@user), class: 'linkcompanion'%></button>